spring.application.name=api-gateway

server.port=8082


# ==============================
# API Gateway Routes
# ==============================

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**


# Order Service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/orders/**


# ==============================
# Actuator
# ==============================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always